/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HealthPackagesRouteImport } from './routes/health-packages'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BloodTestsRouteImport } from './routes/blood-tests'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as MagazineIdRouteImport } from './routes/magazine.$id'
import { Route as HospitalIdRouteImport } from './routes/hospital.$id'
import { Route as DoctorIdRouteImport } from './routes/doctor.$id'
import { Route as ClinicIdRouteImport } from './routes/clinic.$id'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as TabsLabTestsRouteImport } from './routes/_tabs.lab-tests'
import { Route as TabsHospitalsRouteImport } from './routes/_tabs.hospitals'
import { Route as TabsFindDoctorsRouteImport } from './routes/_tabs.find-doctors'
import { Route as TabsExploreRouteImport } from './routes/_tabs.explore'
import { Route as TabsClinicsRouteImport } from './routes/_tabs.clinics'
import { Route as TabsAccountRouteImport } from './routes/_tabs.account'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthPackagesRoute = HealthPackagesRouteImport.update({
  id: '/health-packages',
  path: '/health-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodTestsRoute = BloodTestsRouteImport.update({
  id: '/blood-tests',
  path: '/blood-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const MagazineIdRoute = MagazineIdRouteImport.update({
  id: '/magazine/$id',
  path: '/magazine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIdRoute = HospitalIdRouteImport.update({
  id: '/hospital/$id',
  path: '/hospital/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicIdRoute = ClinicIdRouteImport.update({
  id: '/clinic/$id',
  path: '/clinic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLabTestsRoute = TabsLabTestsRouteImport.update({
  id: '/lab-tests',
  path: '/lab-tests',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHospitalsRoute = TabsHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => TabsRoute,
} as any)
const TabsFindDoctorsRoute = TabsFindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => TabsRoute,
} as any)
const TabsExploreRoute = TabsExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => TabsRoute,
} as any)
const TabsClinicsRoute = TabsClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountRoute = TabsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/blood-tests': typeof BloodTestsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/following': typeof FollowingRoute
  '/health-packages': typeof HealthPackagesRoute
  '/legal': typeof LegalRoute
  '/saved': typeof SavedRoute
  '/account': typeof TabsAccountRoute
  '/clinics': typeof TabsClinicsRoute
  '/explore': typeof TabsExploreRoute
  '/find-doctors': typeof TabsFindDoctorsRoute
  '/hospitals': typeof TabsHospitalsRoute
  '/lab-tests': typeof TabsLabTestsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clinic/$id': typeof ClinicIdRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/magazine/$id': typeof MagazineIdRoute
}
export interface FileRoutesByTo {
  '/blood-tests': typeof BloodTestsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/following': typeof FollowingRoute
  '/health-packages': typeof HealthPackagesRoute
  '/legal': typeof LegalRoute
  '/saved': typeof SavedRoute
  '/account': typeof TabsAccountRoute
  '/clinics': typeof TabsClinicsRoute
  '/explore': typeof TabsExploreRoute
  '/find-doctors': typeof TabsFindDoctorsRoute
  '/hospitals': typeof TabsHospitalsRoute
  '/lab-tests': typeof TabsLabTestsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clinic/$id': typeof ClinicIdRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/magazine/$id': typeof MagazineIdRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/blood-tests': typeof BloodTestsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/following': typeof FollowingRoute
  '/health-packages': typeof HealthPackagesRoute
  '/legal': typeof LegalRoute
  '/saved': typeof SavedRoute
  '/_tabs/account': typeof TabsAccountRoute
  '/_tabs/clinics': typeof TabsClinicsRoute
  '/_tabs/explore': typeof TabsExploreRoute
  '/_tabs/find-doctors': typeof TabsFindDoctorsRoute
  '/_tabs/hospitals': typeof TabsHospitalsRoute
  '/_tabs/lab-tests': typeof TabsLabTestsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/clinic/$id': typeof ClinicIdRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/magazine/$id': typeof MagazineIdRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blood-tests'
    | '/cart'
    | '/checkout'
    | '/following'
    | '/health-packages'
    | '/legal'
    | '/saved'
    | '/account'
    | '/clinics'
    | '/explore'
    | '/find-doctors'
    | '/hospitals'
    | '/lab-tests'
    | '/article/$slug'
    | '/city/$slug'
    | '/clinic/$id'
    | '/doctor/$id'
    | '/hospital/$id'
    | '/magazine/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blood-tests'
    | '/cart'
    | '/checkout'
    | '/following'
    | '/health-packages'
    | '/legal'
    | '/saved'
    | '/account'
    | '/clinics'
    | '/explore'
    | '/find-doctors'
    | '/hospitals'
    | '/lab-tests'
    | '/article/$slug'
    | '/city/$slug'
    | '/clinic/$id'
    | '/doctor/$id'
    | '/hospital/$id'
    | '/magazine/$id'
    | '/'
  id:
    | '__root__'
    | '/_tabs'
    | '/blood-tests'
    | '/cart'
    | '/checkout'
    | '/following'
    | '/health-packages'
    | '/legal'
    | '/saved'
    | '/_tabs/account'
    | '/_tabs/clinics'
    | '/_tabs/explore'
    | '/_tabs/find-doctors'
    | '/_tabs/hospitals'
    | '/_tabs/lab-tests'
    | '/article/$slug'
    | '/city/$slug'
    | '/clinic/$id'
    | '/doctor/$id'
    | '/hospital/$id'
    | '/magazine/$id'
    | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  BloodTestsRoute: typeof BloodTestsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FollowingRoute: typeof FollowingRoute
  HealthPackagesRoute: typeof HealthPackagesRoute
  LegalRoute: typeof LegalRoute
  SavedRoute: typeof SavedRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CitySlugRoute: typeof CitySlugRoute
  ClinicIdRoute: typeof ClinicIdRoute
  DoctorIdRoute: typeof DoctorIdRoute
  HospitalIdRoute: typeof HospitalIdRoute
  MagazineIdRoute: typeof MagazineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-packages': {
      id: '/health-packages'
      path: '/health-packages'
      fullPath: '/health-packages'
      preLoaderRoute: typeof HealthPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-tests': {
      id: '/blood-tests'
      path: '/blood-tests'
      fullPath: '/blood-tests'
      preLoaderRoute: typeof BloodTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/magazine/$id': {
      id: '/magazine/$id'
      path: '/magazine/$id'
      fullPath: '/magazine/$id'
      preLoaderRoute: typeof MagazineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$id': {
      id: '/hospital/$id'
      path: '/hospital/$id'
      fullPath: '/hospital/$id'
      preLoaderRoute: typeof HospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$id': {
      id: '/clinic/$id'
      path: '/clinic/$id'
      fullPath: '/clinic/$id'
      preLoaderRoute: typeof ClinicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/lab-tests': {
      id: '/_tabs/lab-tests'
      path: '/lab-tests'
      fullPath: '/lab-tests'
      preLoaderRoute: typeof TabsLabTestsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/hospitals': {
      id: '/_tabs/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof TabsHospitalsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/find-doctors': {
      id: '/_tabs/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof TabsFindDoctorsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/explore': {
      id: '/_tabs/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof TabsExploreRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/clinics': {
      id: '/_tabs/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof TabsClinicsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account': {
      id: '/_tabs/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof TabsAccountRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAccountRoute: typeof TabsAccountRoute
  TabsClinicsRoute: typeof TabsClinicsRoute
  TabsExploreRoute: typeof TabsExploreRoute
  TabsFindDoctorsRoute: typeof TabsFindDoctorsRoute
  TabsHospitalsRoute: typeof TabsHospitalsRoute
  TabsLabTestsRoute: typeof TabsLabTestsRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAccountRoute: TabsAccountRoute,
  TabsClinicsRoute: TabsClinicsRoute,
  TabsExploreRoute: TabsExploreRoute,
  TabsFindDoctorsRoute: TabsFindDoctorsRoute,
  TabsHospitalsRoute: TabsHospitalsRoute,
  TabsLabTestsRoute: TabsLabTestsRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  BloodTestsRoute: BloodTestsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FollowingRoute: FollowingRoute,
  HealthPackagesRoute: HealthPackagesRoute,
  LegalRoute: LegalRoute,
  SavedRoute: SavedRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CitySlugRoute: CitySlugRoute,
  ClinicIdRoute: ClinicIdRoute,
  DoctorIdRoute: DoctorIdRoute,
  HospitalIdRoute: HospitalIdRoute,
  MagazineIdRoute: MagazineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
