/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthPackagesRouteImport } from './routes/health-packages'
import { Route as BloodTestsRouteImport } from './routes/blood-tests'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as HospitalIdRouteImport } from './routes/hospital.$id'
import { Route as DoctorIdRouteImport } from './routes/doctor.$id'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as TabsLabTestsRouteImport } from './routes/_tabs.lab-tests'
import { Route as TabsHospitalsRouteImport } from './routes/_tabs.hospitals'
import { Route as TabsFindDoctorsRouteImport } from './routes/_tabs.find-doctors'
import { Route as TabsExploreRouteImport } from './routes/_tabs.explore'
import { Route as TabsClinicsRouteImport } from './routes/_tabs.clinics'

const HealthPackagesRoute = HealthPackagesRouteImport.update({
  id: '/health-packages',
  path: '/health-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodTestsRoute = BloodTestsRouteImport.update({
  id: '/blood-tests',
  path: '/blood-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const HospitalIdRoute = HospitalIdRouteImport.update({
  id: '/hospital/$id',
  path: '/hospital/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsLabTestsRoute = TabsLabTestsRouteImport.update({
  id: '/lab-tests',
  path: '/lab-tests',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHospitalsRoute = TabsHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => TabsRoute,
} as any)
const TabsFindDoctorsRoute = TabsFindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => TabsRoute,
} as any)
const TabsExploreRoute = TabsExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => TabsRoute,
} as any)
const TabsClinicsRoute = TabsClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/blood-tests': typeof BloodTestsRoute
  '/health-packages': typeof HealthPackagesRoute
  '/clinics': typeof TabsClinicsRoute
  '/explore': typeof TabsExploreRoute
  '/find-doctors': typeof TabsFindDoctorsRoute
  '/hospitals': typeof TabsHospitalsRoute
  '/lab-tests': typeof TabsLabTestsRoute
  '/city/$slug': typeof CitySlugRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/hospital/$id': typeof HospitalIdRoute
}
export interface FileRoutesByTo {
  '/blood-tests': typeof BloodTestsRoute
  '/health-packages': typeof HealthPackagesRoute
  '/clinics': typeof TabsClinicsRoute
  '/explore': typeof TabsExploreRoute
  '/find-doctors': typeof TabsFindDoctorsRoute
  '/hospitals': typeof TabsHospitalsRoute
  '/lab-tests': typeof TabsLabTestsRoute
  '/city/$slug': typeof CitySlugRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/blood-tests': typeof BloodTestsRoute
  '/health-packages': typeof HealthPackagesRoute
  '/_tabs/clinics': typeof TabsClinicsRoute
  '/_tabs/explore': typeof TabsExploreRoute
  '/_tabs/find-doctors': typeof TabsFindDoctorsRoute
  '/_tabs/hospitals': typeof TabsHospitalsRoute
  '/_tabs/lab-tests': typeof TabsLabTestsRoute
  '/city/$slug': typeof CitySlugRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blood-tests'
    | '/health-packages'
    | '/clinics'
    | '/explore'
    | '/find-doctors'
    | '/hospitals'
    | '/lab-tests'
    | '/city/$slug'
    | '/doctor/$id'
    | '/hospital/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blood-tests'
    | '/health-packages'
    | '/clinics'
    | '/explore'
    | '/find-doctors'
    | '/hospitals'
    | '/lab-tests'
    | '/city/$slug'
    | '/doctor/$id'
    | '/hospital/$id'
    | '/'
  id:
    | '__root__'
    | '/_tabs'
    | '/blood-tests'
    | '/health-packages'
    | '/_tabs/clinics'
    | '/_tabs/explore'
    | '/_tabs/find-doctors'
    | '/_tabs/hospitals'
    | '/_tabs/lab-tests'
    | '/city/$slug'
    | '/doctor/$id'
    | '/hospital/$id'
    | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  BloodTestsRoute: typeof BloodTestsRoute
  HealthPackagesRoute: typeof HealthPackagesRoute
  CitySlugRoute: typeof CitySlugRoute
  DoctorIdRoute: typeof DoctorIdRoute
  HospitalIdRoute: typeof HospitalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health-packages': {
      id: '/health-packages'
      path: '/health-packages'
      fullPath: '/health-packages'
      preLoaderRoute: typeof HealthPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-tests': {
      id: '/blood-tests'
      path: '/blood-tests'
      fullPath: '/blood-tests'
      preLoaderRoute: typeof BloodTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/hospital/$id': {
      id: '/hospital/$id'
      path: '/hospital/$id'
      fullPath: '/hospital/$id'
      preLoaderRoute: typeof HospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/lab-tests': {
      id: '/_tabs/lab-tests'
      path: '/lab-tests'
      fullPath: '/lab-tests'
      preLoaderRoute: typeof TabsLabTestsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/hospitals': {
      id: '/_tabs/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof TabsHospitalsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/find-doctors': {
      id: '/_tabs/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof TabsFindDoctorsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/explore': {
      id: '/_tabs/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof TabsExploreRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/clinics': {
      id: '/_tabs/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof TabsClinicsRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsClinicsRoute: typeof TabsClinicsRoute
  TabsExploreRoute: typeof TabsExploreRoute
  TabsFindDoctorsRoute: typeof TabsFindDoctorsRoute
  TabsHospitalsRoute: typeof TabsHospitalsRoute
  TabsLabTestsRoute: typeof TabsLabTestsRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsClinicsRoute: TabsClinicsRoute,
  TabsExploreRoute: TabsExploreRoute,
  TabsFindDoctorsRoute: TabsFindDoctorsRoute,
  TabsHospitalsRoute: TabsHospitalsRoute,
  TabsLabTestsRoute: TabsLabTestsRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  BloodTestsRoute: BloodTestsRoute,
  HealthPackagesRoute: HealthPackagesRoute,
  CitySlugRoute: CitySlugRoute,
  DoctorIdRoute: DoctorIdRoute,
  HospitalIdRoute: HospitalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
